services:
  app:
    command: ""
    watch:

  firebase: {}

  certbot:
    build:
      dockerfile: ./Dockerfile
      context: ./certbot
      args:
        CERTBOT_EMAIL: ${CERTBOT_EMAIL}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
    command: certonly -v -d "${PUBLIC_DOMAIN}" -d "www.${PUBLIC_DOMAIN}"
    volumes:
      - ./certbot/volumes/var/lib/letsencrypt/:/var/lib/letsencrypt/
      - ./certbot/volumes/etc/letsencrypt/:/etc/letsencrypt/
      - ./certbot/volumes/var/www/html/.well-known/:/var/www/html/.well-known/
