services:
  app:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./app
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}

    ports:
      # NOTE: 80 is required for certbot challenge
      - "80:80"
      - "443:443"

    volumes:
      - ./certbot/volumes/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/volumes/var/www/html/.well-known:/var/www/html/.well-known
  db:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./db
      args:
        PORT: 3306
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}

    ports:
      - 3306:3306

    volumes:
      - ./db/volumes/data:/var/lib/mysql

  phpmyadmin:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./phpmyadmin
      args:
        UPLOAD_LIMIT: 100G
        PORT: 8443

    ports:
      - 8443:8443

    volumes:
      - ./certbot/volumes/etc/letsencrypt:/etc/letsencrypt

  certbot:
    build:
      dockerfile: ./Dockerfile
      context: ./certbot
      args:
        CERTBOT_EMAIL: ${CERTBOT_EMAIL}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
    command: certonly -d "${PUBLIC_DOMAIN}" -d "www.${PUBLIC_DOMAIN}"
    volumes:
      - ./certbot/volumes/var/lib/letsencrypt/:/var/lib/letsencrypt/
      - ./certbot/volumes/etc/letsencrypt/:/etc/letsencrypt/
      - ./certbot/volumes/var/www/html/.well-known/:/var/www/html/.well-known/
