services:
  app:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./app
      args:
        NODE_ENV: ${ENVIRONMENT}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}

    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /app/src

        - action: sync
          path: ./app/client/src
          target: /app/client/src

        - action: sync
          path: ./app/client/react-firebase-chat/src
          target: /app/client/react-firebase-chat/src

        - action: rebuild
          path: ./app/package.json
          target: /app

        - action: rebuild
          path: ./app/client/package.json
          target: /app/client

        - action: rebuild
          path: ./app/client/react-firebase-chat/package.json
          target: /app/client/react-firebase-chat

    ports:
      # NOTE: 80 is required for certbot ACME challenge
      - "80:${APP_PORT}"
      - "443:${APP_PORT}"

    # NOTE: Overriden in prod
    command: ["npm", "run", "dev"]

    volumes:
      - ./certbot/volumes/etc/letsencrypt:/certbot/volumes/etc/letsencrypt
      - ./certbot/volumes/var/www/html/.well-known:/var/www/html/.well-known
  db:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./db
      args:
        PORT: 3306
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}

    ports:
      - 3306:3306

    volumes:
      - ./db/volumes/data:/var/lib/mysql

  phpmyadmin:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./phpmyadmin
      args:
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
        UPLOAD_LIMIT: 100G

    ports:
      - 8080:8080
      - 8443:8443

    volumes:
      - ./certbot/volumes/etc/letsencrypt:/etc/letsencrypt
