on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # For installing github repositories as dependencies
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm config set @jdboris:registry=http://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm remove @jdboris/react-firebase-chat
          npm i @jdboris/react-firebase-chat
          npm remove @jdboris/stream-site
          npm i @jdboris/stream-site
          npm install
          npm run build
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.SERVER }}
          local-dir: ./build/
          server-dir: default/
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          port: 21
