on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # For installing github repositories as dependencies
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          export NODE_ENV=production
          npm config set @jdboris:registry=https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm install --omit=dev
          npm run build
        env:
          CI: false

      - name: Deploy with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "--delete -rltgoDzvO"
          SOURCE: "/dist/"
          REMOTE_HOST: ${{ secrets.SSH_SERVER }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: /var/www/default/
          EXCLUDE: "**/.git*, **/.git*/**, **/.github*, **/.github*/**, .gitattributes, .gitignore, LICENSE, README.md, NOTES.txt, package-lock.json, package.json"
